Updated/better bootstrap script

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -1,20 +1,20 @@
 #! /bin/sh
 # bootstrap        Bootstrap Script
-# Copyright (C) 2000, 2002, ETG, Inc. All Rights Reserved.
+# Copyright (C) 2000, 2002, 2003, 2005, ETG, Inc. All Rights Reserved.
 #
 # This file is proprietary and confidential and must not be distributed without the 
 # express permission of the copyright holder.
 #
 # See file COPYING for details.
 # 
-# $Id: bootstrap,v 1.2 2002/12/21 22:45:40 jshiffer Exp $
+# $Id: bootstrap,v 1.2 2003/06/10 03:53:34 jshiffer Exp $
 # 
 # 
 # History:  -jshiffer 12/19/00 3:53pm: Created.
 
 
-(test -d aux) || {
- mkdir -p aux;
+(test -d aux_files) || {
+ mkdir -p aux_files;
 }
 
 # libtoolize generates support for libtool
@@ -22,17 +22,55 @@
 # aclocal generates aclocal.m4 by scanning configure.in
 # automake generates Makefile.in by scanning Makefile.am
 # autoconf generates configure by scanning configure.in
+progvar ()
+{
+    #
+    # see if the first choice exists
+    #
+    local VV=$1; shift
+    local i
+    local R
+
+    eval R=\\\$"$VV"
+    eval R=$R
+
+    if [ x${R} == x"" ]; then
+
+	for (( i=1; i<=$#; i++ )); do
+	    type $1 > /dev/null 2>&1
+	    if [[ $? = 0 ]]; then
+		V=$1
+	    fi
+	    shift;
+	done
+    else
+	# the environment alread sets it
+	return;
+    fi
+
+
+    eval $VV=$V
+    unset V
+}
+
+error () {
+    echo "$1: failed with $?"
+    exit 1
+}
+
+# find the apps and set if necessary
+progvar LIBTOOLIZE libtoolize
+progvar ACLOCAL aclocal
+progvar AUTOHEADER autoheader
+progvar AUTOCONF autoconf
+progvar AUTOMAKE automake
+progvar AUTORECONF autoreconf
+
+
 
 set -x
-if [ -f /usr/bin/glibtoolize ]; then
- LIBTOOLIZE=glibtoolize
-else
- LIBTOOLIZE=libtoolize
-fi
-
-${LIBTOOLIZE} --automake --copy --force && \
-aclocal -I aux && \
-autoheader && \
-autoconf && \
-automake --add-missing --copy --foreign
-
+${ACLOCAL} -I aux_files || error "${ACLOCAL}"
+#${AUTOHEADER} || error "${AUTOHEADER}"
+${LIBTOOLIZE} --automake --copy --force --install || error "${LIBTOOLIZE}"
+${AUTOCONF} || error "${AUTOCONF}"
+${AUTOMAKE} --add-missing --copy --foreign || error "${AUTOMAKE}"
